---
name: Run tests

"on": [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install package
        run: python setup.py install
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install dukpy
          python -m pip install pytest
      - name: clone vpl-web
        uses: actions/checkout@master
        with:
          repository: epfl-mobots/vpl-web
      - name: Run tests
        run: python -m pytest tests/test*
